import ContextProvider from "./contextProvider";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html dir="rtl" lang="en">
      
      <body className="light light_blue">
        <ContextProvider>{children}</ContextProvider>
      
      </body>
    </html>
  );
}
